/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 3.5 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n adder4 -lang verilog -synth synplify -bus_exp 7 -bb -arch se5c00 -type add -width 4 -unsigned -port ci -port co  */
/* Wed Sep 21 12:32:20 2022 */


`timescale 1 ns / 1 ps
module adder4 (DataA, DataB, Cin, Result, Cout)/* synthesis NGD_DRC_MASK=1 */;
    input wire [3:0] DataA;
    input wire [3:0] DataB;
    input wire Cin;
    output wire [3:0] Result;
    output wire Cout;

    wire scuba_vhi;
    wire precin;
    wire co0;
    wire co1;
    wire co2d;
    wire co2;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B precin_inst17 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(precin), .S0(), .S1());

    FADD2B addsub_0 (.A0(Cin), .A1(DataA[0]), .B0(Cin), .B1(DataB[0]), .CI(precin), 
        .COUT(co0), .S0(), .S1(Result[0]));

    FADD2B addsub_1 (.A0(DataA[1]), .A1(DataA[2]), .B0(DataB[1]), .B1(DataB[2]), 
        .CI(co0), .COUT(co1), .S0(Result[1]), .S1(Result[2]));

    FADD2B addsub_2 (.A0(DataA[3]), .A1(scuba_vlo), .B0(DataB[3]), .B1(scuba_vlo), 
        .CI(co1), .COUT(co2), .S0(Result[3]), .S1(Cout));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B addsubd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(co2), .COUT(), .S0(co2d), .S1());



    // exemplar begin
    // exemplar end

endmodule
