/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 3.5 */
/* Wed Sep 21 12:32:20 2022 */

/* parameterized module instance */
adder4 __ (.DataA( ), .DataB( ), .Cin( ), .Result( ), .Cout( ));
